### ISSUE TITLE
Bug: type 'Location' is not a subtype of type 'Map<String, dynamic>' in type cast

### ISSUE THREAD

**Issue by bugrevealingbme** [ueman/passkit#99]
My test pass key: https://www.passsource.com/pass/create.php?hashedSerialNumber=eNortjIysVJyMwl3Kyty9vN0Nk5Piczz9s5K89NPt7VVsgZcMJrHCXI,&

Another package. pass_flutter

My code:  PkPassWidget(
                  pass:
                      PkPass(pass: PassData.fromJson(passFile!.pass.toJson()))),

**Comment by ueman** [comment]
Can you try the following code?


```dart
PkPassWidget(pass: passFile),
```
or
```dart
PkPassWidget(
  pass: PkPass(pass: passFile!.pass))
),
```

That makes the code look a bit better and you avoid a serialization and deserialization, which should improve your performance a tiny bit, too.

I'm not sure what exactly you're doing, but the following code works just fine for me:

```dart
import 'dart:io';

import 'package:passkit/passkit.dart';
import 'package:test/test.dart';

void main() {
  test('can read pass with locations', () async {
    // test.pkpass is the file from https://www.passsource.com/pass/create.php?hashedSerialNumber=eNortjIysVJyMwl3Kyty9vN0Nk5Piczz9s5K89NPt7VVsgZcMJrHCXI,&
    final bytes = File('test.pkpass').readAsBytesSync();

    final pkPass = PkPass.fromBytes(bytes, skipSignatureVerification: true); // Apparently the certificate of that example pass is expired, so we need to skip the signature check to read it
    expect(pkPass.pass.locations, isNotEmpty);
  });
}

```

**Comment by bugrevealingbme** [comment]
No problem reading it as a file. But I want to import as json.
